config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  resources :trips

  resources :users

  get '/auth/facebook', as: "facebook_login"
  match 'auth/facebook/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  get 'logout' => 'sessions#destroy', :as => :logout

  get "/:page" => "static#show"
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :trip_name
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :trips

  def self.from_omniauth(auth_hash)
    where(auth_hash.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth_hash.provider
      user.uid = auth_hash.uid
      user.name = auth_hash.info.name
      user.email = auth_hash.info.email
      user.image = auth_hash.info.image
      user.oauth_token = auth_hash.credentials.token
      user.oauth_expires_at = Time.at(auth_hash.credentials.expires_at)
      user.save!
    end
  end

  def facebook
    @facebook ||= Koala::Facebook::API.new(oauth_token)
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :logged_in?
  helper_method :authorized_user?

  private 
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
      !!current_user
    end

    def authorized_user?(trip)
      logged_in? && trip.user.include?(current_user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.from_omniauth(env["omniauth.auth"])
    session[:current_user] = @user
    session[:user_id] = @user.id
    redirect_to new_trip_path, :notice => "Congrats, you're logged in!" 
  end

  # def new 
  #   session[:return_to] = request.referer
  # end

  def destroy
    session[:user_id] = nil
    redirect_to root_url #, :notice => "Signed out!"
  end

  protected

    def auth_hash
      request.env['omniauth.auth'] 
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def show
    render params[:page]
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    # @trips = Trip.all
    redirect_to root_url
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    unless @trip.user == current_user
      redirect_to root_url
    end
  end

  # GET /trips/new
  def new
    if logged_in?
      @trip = Trip.new # this was original - the method was added
    else
      redirect_to root_url, :flash => { :error => "Make sure you're logged in!!" }
    end
  end

  # GET /trips/1/edit
  def edit
    if !logged_in?
      redirect_to root_path, :flash => { :error => "Make sure you're logged in!" }
    elsif !question_author?
      redirect_to root_url, :flash => { :error => "You can't edit someone else's trip!" }
    end
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    if (logged_in? && trip_author?) 
      @trip.destroy
      redirect_to root_url
    else
      redirect_to root_url, :flash => { :error => "You can't delete someone else's trip!" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:trip_name, :location, :user_id, :to_pack, :to_do, :budget)
    end

    def trip_author?
      @trip.user == current_user
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    redirect_to root_url
  end

  # GET /users/1
  # GET /users/1.json
  def show
    unless current_user.id == params[:id].to_i
      redirect_to root_url
    end
  end

  # GET /users/new
  def new
    redirect_to root_url
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  # def create
  #   @user = User.new(user_params)

  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to @user, notice: 'User was successfully created.' }
  #       format.json { render :show, status: :created, location: @user }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  # def update
  #   respond_to do |format|
  #     if @user.update(user_params)
  #       format.html { redirect_to @user, notice: 'User was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @user }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /users/1
  # DELETE /users/1.json
  # def destroy
  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def user_params
    #   params.require(:user).permit(:name, :provider, :uid, :email, :image, :oauth_token, :oauth_expires_at)
    # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.erb
<header>
  <center>
  <div id="index-cover">
    <h1>Travel App</span>NY</h1>
    <h2>Tagline!</h2>
    <br><br>
    <br><br>
    <br><br>
    <% if !current_user %>
      <a href="/auth/facebook">Log in with Facebook</a>
    <% end %>
  </div>
  <br>
  <br>
  <br>
  </center>
</header>

app/views/layouts/_header.html.erb
<% if current_user %>
  <li><%= link_to "MY TRIPS!!", current_user %></li>
  <li><a>Hey, <%= current_user.name.split(" ")[0] %>!</a></li>
  <li><img src="<%= current_user.image %>"></li>
  <li><%= link_to "Log Out", logout_path %></li>
<% else %>
  <li><%= link_to "Log in with Facebook", facebook_login_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travel</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
  <meta name="keywords" content="Koren Leslie Cohen, Christina Leuci, travel journal, online travel journal, travel budget calculator, travel application, The Flatiron School"/>
  <meta name="description" content="description">
  <title>Title</title>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :trip_name %><br>
    <%= f.text_field :trip_name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
<!--   <div class="field"> -->
    <%#= f.label :user_id %><br>
    <%#= f.number_field :user_id %>
<!--   </div> -->
<div class="field">
  <%= f.hidden_field :user_id, :value => session["user_id"] %>
    <%= f.label :to_pack %><br>
    <%= f.text_area :to_pack %>
  </div>
  <div class="field">
    <%= f.label :to_do %><br>
    <%= f.text_area :to_do %>
  </div>
  <div class="field">
    <%= f.label :budget %><br>
    <%= f.number_field :budget %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<h1>Listing trips</h1>

<table>
  <thead>
    <tr>
      <th>Trip name</th>
      <th>Location</th>
      <th>User</th>
      <th>To pack</th>
      <th>To do</th>
      <th>Budget</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.trip_name %></td>
        <td><%= trip.location %></td>
        <td><%= trip.user_id %></td>
        <td><%= trip.to_pack %></td>
        <td><%= trip.to_do %></td>
        <td><%= trip.budget %></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Trip name:</strong>
  <%= @trip.trip_name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @trip.location %>
</p>

<p>
  <strong>User:</strong>
  <%= @trip.user_id %>
</p>

<p>
  <strong>To pack:</strong>
  <%= @trip.to_pack %>
</p>

<p>
  <strong>To do:</strong>
  <%= @trip.to_do %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @trip.budget %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Provider</th>
      <th>Uid</th>
      <th>Email</th>
      <th>Image</th>
      <th>Oauth token</th>
      <th>Oauth expires at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.provider %></td>
        <td><%= user.uid %></td>
        <td><%= user.email %></td>
        <td><%= user.image %></td>
        <td><%= user.oauth_token %></td>
        <td><%= user.oauth_expires_at %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%#= link_to 'Edit', edit_user_path(user) %></td>
        <td><%#= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<h2>My trips</h2>

<% @user.trips.each do |trip| %>
    <h2><%=link_to trip.trip_name, trip %></h2>
<% end %>

<%= link_to 'New Trip', new_trip_path %> |
<%= link_to 'Back', users_path %>